workflows:
  android-workflow:
    name: Mission APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Install dependencies and Capacitor
        script: |
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/android
      - name: Initialize and Add Android platform
        script: |
          npx cap init Mission com.ancyexantus.mission --web-dir dist
          npx cap add android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
